### ISSUE TITLE
模型权重和数据集相关问题

### ISSUE THREAD

**Issue by helloyizhengjun** [AIR-THU/DAIR-V2X#13]
请问数据集得challenge大概什么时候会出现？
请问ImvoxelNet关于车路协同数据集得.pth权重文件大概什么时候会出现？

**Comment by haibao-yu** [comment]
We have added the ImvoxelNet models for VIC3D late fusion at https://github.com/AIR-THU/DAIR-V2X/tree/main/configs/vic3d/late-fusion-image/imvoxelnet. Pease note that the results will be somewhat different from the paper due to the updated code. Everything is subject to the actual implementation results.
