### ISSUE TITLE
ImvoxelNet相关

### ISSUE THREAD

**Issue by helloyizhengjun** [AIR-THU/DAIR-V2X#14]
请问ImvoxelNet训练车路协同数据集是直接使用原始模型网络还是有些更改，请问有没有相关介绍和说明？

**Comment by haibao-yu** [comment]
We have added the ImvoxelNet models for VIC3D late fusion at https://github.com/AIR-THU/DAIR-V2X/tree/main/configs/vic3d/late-fusion-image/imvoxelnet. Pease note that the results will be somewhat different from the paper due to the updated code. Everything is subject to the actual implementation results.
