### ISSUE TITLE
How the image is resized to 1920 by 1080? LiDAR on image alignment

### ISSUE THREAD

**Issue by thaotrongtran** [AIR-THU/DAIR-V2X#25]
Thank you for responding to issues recently.
I wonder how the image is resized to have the size 1920 by 1080 when the camera sensor is  4096x2160. Also, does this process affect the alignment of LiDAR on an image? For example, for a stationary object below, why the signs are not aligned correctly using the provided intrinsic matrix? This object is stationary, so there shouldn't be due to a time difference between LiDAR capture time and image capture time.
![image](https://user-images.githubusercontent.com/35986098/204096761-962fcd48-ff14-459c-9849-cc445fa75f49.png)

**Comment by haibao-yu** [comment]
Thanks for your feedback. Because of the lack of experience at the beginning, our infrastructure-side cameras and LiDARs were calibrated separately, and there was a certain calibration projection error when associating these sensor data. We re-match the sensor data and ensured that most of the stationary targets can be matched, but we still cannot completely cover these problems.
