### ISSUE TITLE
关于在纯雷达标注中存在的标注缺失问题

### ISSUE THREAD

**Issue by hehualin-tut** [AIR-THU/DAIR-V2X#42]
我注意到一个问题，在您的官方网站中所提供的数据集里，激光雷达的标注是缺失的，我猜想您是按照相机视角的遮挡来进行标注从而导致标注缺失，您可以查看下_000917.json_并将其bondingbox投影到激光雷达坐标系，就会发现在近处的一些明显的车辆没有标注，这对于纯激光雷达检测是不允许的，我也很感谢您的开源工作，但这真的很困扰，最后再提一句投影不准确问题。

**Comment by haibao-yu** [comment]
> 我注意到一个问题，在您的官方网站中所提供的数据集里，激光雷达的标注是缺失的，我猜想您是按照相机视角的遮挡来进行标注从而导致标注缺失，您可以查看下_000917.json_并将其bondingbox投影到激光雷达坐标系，就会发现在近处的一些明显的车辆没有标注，这对于纯激光雷达检测是不允许的，我也很感谢您的开源工作，但这真的很困扰，最后再提一句投影不准确问题。

Thanks for you feedback. 

For the annotation issue, we use 2-3D joint labelling approach to annotate the 3D bounding box for our dataset, so we only provide  annotations for those objects appearing both in images and point clouds. This is similar to the annotation in KITTI dataset. 

For the projection issue, the dataset does have the problem of projection mismatch caused by calibration error. We hope we can solve these problem in our newer dataset.
