### ISSUE TITLE
DAIR-V2X dataset 

### ISSUE THREAD

**Issue by huangxiang686990** [AIR-THU/DAIR-V2X#68]
Does the dataset only collect a intersection information? I find the dataset only uses a roadside Lidar to collect the vehicle information.

**Comment by wanghangege** [comment]
In order to promote the joint creation of data-driven vehicle-road collaborative autonomous driving by academia and industry, Tsinghua University Intelligent Industry Research Institute (AIR) launched the world's first vehicle-road collaborative autonomous driving dataset DAIR- V2X, jointly explore the landing mode of vehicle-road collaborative autonomous driving.
